### ISSUE TITLE
I can't check the operation, so please tell me how to deal with it.

### ISSUE THREAD

**Issue by AngelSeed** [Eternita-S/DSREyeLocator#2]
https://gyazo.com/7a0607429bd78d85b37359ca7ac0a11c

I entered the content and it is not displayed due to evil eyes, etc. Is there any problem?
I can't do it with a Japanese client ...

**Comment by Limiana** [comment]
Hello! It is supposed to work on all languages. Can you please make sure  that you are using latest, 1.0.0.4 version?
If it is latest version, please target King Thordan and send me screenshot of plugin's configuration window

**Comment by AngelSeed** [comment]
The version was correct.
I will check it again tomorrow.
Thank you

**Comment by AngelSeed** [comment]
I'm sorry I made a mistake.
I was able to confirm the operation.
I am always grateful for your help.

**Comment by Limiana** [comment]
thanks for the feedback and good luck in raid!
